### PR TITLE
Fixed frame

### LINKED ISSUE #5: Enhancement: Fixate the frame
I was told it would be great idea if it was possible to make the frame immovable via a setting.
I think make it immovable by default (thus breaking backward compatibility) and make it possible to unlock.

### PR DESCRIPTION
**Pull request by KalitaAlexey**
изображение
изображение
изображение
изображение

Localization is required for "General", "Buttons", "Lock frame position".
I suggest that russian localization should be "Общие", "Кнопки", "Зафиксировать позицию рамки", accordingly.

Also, I don't like that buttons are at the center of the page, other addons don't seem to do it.

Fixes #5

### CODE REVIEW

File: QuickChat/Configuration/ButtonsFrame.lua [hunk 1]
```diff
@@ -0,0 +1,38 @@
...
+frame.parent = QuickChat.mainConfigurationFrame.name
+InterfaceOptions_AddCategory(frame)
+QuickChat.buttonsConfigurationFrame = frame
+
+function frame:OnAddonLoaded()
+    local l = QuickChat_GetLocalization()
+    
+    local info = frame:CreateFontString("QuickChat_BtnCfgFrame_Info", "OVERLAY", "GameFontHighlight")
+    info:SetPoint("TOP", frame, "TOP", 0, -40)
+    info:SetText(l["INFO"])
```
Comment (KalitaAlexey) [inline QuickChat/Configuration/ButtonsFrame.lua:12]: Assuming you want to add "Help" text for "Buttons" page, this "INFO" need to be into something meaningful.

File: QuickChat/Configuration/ButtonsFrame.lua [hunk 2]
```diff
@@ -0,0 +1,38 @@
...
+        QC_Settings.enableBreak = checked
+    end)
+
+    frame:CreateCheckButton("Reload", l["RELOAD"], QC_Settings.enableReload, function(checked)
+        QC_Settings.enableReload = checked
+    end)
+end
+
+local previousButton = nil
+function frame:CreateCheckButton(name, text, checked, onCheckedChanged)
```
Comment (KalitaAlexey) [inline QuickChat/Configuration/ButtonsFrame.lua:36]: It's required to define the function for `frame` because otherwise it's global and it messes with similar function in GeneralFrame.lua.

File: QuickChat/Configuration/GeneralFrame.lua [hunk 3]
```diff
@@ -0,0 +1,16 @@
...
+InterfaceOptions_AddCategory(frame)
+QuickChat.generalConfigurationFrame = frame
+
+function frame:OnAddonLoaded()
+    frame:CreateCheckButton("LockFramePosition", "Lock frame position", QC_Settings.lockFramePosition, function(checked)
+        QC_Settings.lockFramePosition = checked
+    end)
+end
+
+local previousButton = nil
```
Comment (KalitaAlexey) [inline QuickChat/Configuration/GeneralFrame.lua:13]: All this "previousButton" isn't used yet, but I think we'll add more stuff later.

File: QuickChat/Configuration/MainFrame.lua [hunk 4]
```diff
@@ -0,0 +1,19 @@
+local frame = CreateFrame("Frame", "QuickChat_MainCfgFrame", UIParent)
+frame.name = "QuickChat"
+InterfaceOptions_AddCategory(frame)
+QuickChat.mainConfigurationFrame = frame
+
+function frame:OnAddonLoaded()
+    QuickChat.generalConfigurationFrame:OnAddonLoaded()
+    QuickChat.buttonsConfigurationFrame:OnAddonLoaded()
```
Comment (KalitaAlexey) [inline QuickChat/Configuration/MainFrame.lua:8]: New pages need to be called here.

File: QuickChat/QuickChat.toc [hunk 5]
```diff
@@ -11,4 +11,4 @@ Fix\lib.xml
 
 main.lua
 Fix.lua
-CfgFrame.lua
\ No newline at end of file
+Configuration\Configuration.xml
```
Comment (KalitaAlexey) [inline QuickChat/QuickChat.toc:14]: Configuration pages use `QuickChat` variable that's defined in main.lua
